---
# grayst0-live-trader  ▸  Cloud Build pipeline
# ───────────────────────────────────────────────────────────────────────────────

logsBucket: gs://grayst0-build-logs-1746335095      # central log bucket

options:
  substitutionOption: ALLOW_LOOSE                  # ignore stray _VARS

# ──────────────────────────────  secrets  ─────────────────────────────────────
availableSecrets:
  secretManager:
    - versionName: projects/$(PROJECT_ID)/secrets/GITHUB_PAT/versions/latest
      env: GITHUB_PAT          # will surface as $GITHUB_PAT inside steps

# ──────────────────────────────  build steps  ─────────────────────────────────
steps:

# 0️⃣  Build & test in a clean Python 3.11 image
- id: build-and-test
  name: python:3.11-slim
  entrypoint: bash
  args:
    - -ceu
    - |
      echo "📦 installing deps …"
      pip install -r requirements.txt
      echo "🧪 running smoke tests …"
      pytest tests/smoke

# 1️⃣  Archive workspace → gs://grayst0-deploy/latest.tgz + VERSION
- id: pack-and-upload
  name: gcr.io/cloud-builders/gsutil
  waitFor: ['build-and-test']
  entrypoint: bash
  args:
    - -ceu
    - |
      echo "📦 archiving workspace …"
      tar -czf /workspace/latest.tgz --exclude=.git .
      printf '%s\n' "$SHORT_SHA" > /workspace/VERSION
      gsutil cp /workspace/latest.tgz gs://grayst0-deploy/latest.tgz
      gsutil cp /workspace/VERSION    gs://grayst0-deploy/VERSION

# 2️⃣  Promote to “prod” once sandbox VM writes SMOKE_PASS
- id: promote-if-pass
  name: gcr.io/cloud-builders/gsutil
  waitFor: ['pack-and-upload']
  entrypoint: bash
  args:
    - -ceu
    - |
      echo "🚦 waiting for sandbox SMOKE_PASS …"
      for i in {1..30}; do
        if gsutil cat gs://grayst0-deploy/SMOKE_PASS 2>/dev/null \
            | grep -q "$SHORT_SHA"; then
          echo "✅ sandbox passed – promoting"
          gsutil cp gs://grayst0-deploy/latest.tgz \
                    gs://grayst0-deploy/latest.tgz-prod
          printf '%s\n' "$SHORT_SHA" | gsutil cp - \
                    gs://grayst0-deploy/VERSION-prod
          exit 0
        fi
        sleep 10
      done
      echo "🛑 sandbox did not approve within 5 min"
      exit 1

# 3️⃣  Auto-maintenance that commits changes back to GitHub
- id: make-and-commit-changes
  name: python:3.11-slim
  waitFor: ['promote-if-pass']
  env:
    - GITHUB_PAT=$$GITHUB_PAT            # marks secret as “used”
    - GIT_AUTHOR_NAME=cloudbuild
    - GIT_AUTHOR_EMAIL=ci@grayst0
    - GIT_COMMITTER_NAME=cloudbuild
    - GIT_COMMITTER_EMAIL=ci@grayst0
  entrypoint: bash
  args:
    - -ceu
    - |
      echo "🛠️  auto-maintenance …"
      export GITHUB_TOKEN="$GITHUB_PAT"  # used by gh / git push
      pip install --quiet -r scripts/requirements-auto.txt
      ./scripts/auto-maintain.sh

# ──────────────────────────────  images (none)  ───────────────────────────────
images: []

# ──────────────────────────────  handy subs  ──────────────────────────────────
substitutions:
  _PY_VERSION: "3.11"

