# cloudbuild.yaml  ⟨totally self-contained⟩
# ──────────────────────────────────────────────────────────────────────────────
logsBucket: gs://grayst0-build-logs        # handled earlier

substitutions:
  _DEPLOY_BUCKET: gs://grayst0-deploy      # bundle lands here

steps:
  # 1 – build & smoke-test the repo
  - id: build-and-test
    name: python:3.11-slim
    entrypoint: bash
    args:
      - -ceu
      - |
        echo "📦 installing deps …"
        pip install --quiet --no-cache-dir pytest requests pyyaml -r requirements.txt
        echo "🧪 running smoke tests …"
        python -m pytest -q tests/smoke/

  # 2 – pack the repo and upload (create .tgz in /tmp so tar never rereads it)
  - id: pack-and-upload
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - -ceu
      - |
        echo "📦  archiving workspace …"
        TMP_TGZ="/tmp/latest.tgz"
        tar -czf "${TMP_TGZ}" --exclude=.git .
        echo "$SHORT_SHA" > /tmp/VERSION
        gsutil cp "${TMP_TGZ}"       ${_DEPLOY_BUCKET}/latest.tgz
        gsutil cp /tmp/VERSION       ${_DEPLOY_BUCKET}/VERSION
timeout: 3600s
# ──────────────────────────────────────────────────────────────────────────────
