steps:
  # 1 – Build the runtime image
  - name: gcr.io/cloud-builders/docker
    args: [ "build", ".", "-t", "gcr.io/$PROJECT_ID/trader:$COMMIT_SHA" ]

  # 2 – SSH to the VM and deploy this commit
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - -euo
      - pipefail
      - -c
      - |
          gcloud compute ssh gs-live-trader \
            --zone us-central1-a \
            --quiet \
            --ssh-key-expire-after=30m \
            --ssh-flag="-o StrictHostKeyChecking=no" \
            --command "
              set -e
              cd /opt/gs/grayst0-live-trader
              git config --global --add safe.directory /opt/gs/grayst0-live-trader
              git fetch origin
              git reset --hard \$COMMIT_SHA
              sudo systemctl restart gs-trader
            "

timeout: 900s
options:
  logging: CLOUD_LOGGING_ONLY
