# ─── Cloud Build pipeline (single smoke-test) ──────────────────────────────────
logsBucket: gs://grayst0-build-logs                      # ✅ bucket exists

steps:
# ── 1. run smoke tests directly in the python:3.11-slim image ────────────────
- id: build-and-test
  name: python:3.11-slim
  entrypoint: bash
  args:
    - -c
    - |
      set -euo pipefail
      echo "📦 installing deps …"
      pip install --quiet --no-cache-dir -r requirements.txt
      echo "🧪 running smoke tests …"
      python -m pytest -q tests/smoke/
# ──────────────────────────────────────────────────────────────────────────────

timeout: 900s
options:
  logging: CLOUD_LOGGING_ONLY
