steps:
  # 1 – Build the Docker image locally (for tests / linting only — not pushed)
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "local/grayst0-test:$SHORT_SHA", "."]

  # 2 – Package the repo and drop artifacts in the deploy bucket
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - -c
      - |
        tar -czf /workspace/latest.tgz --exclude=.git .
        echo "$SHORT_SHA" > /workspace/VERSION
        gsutil cp /workspace/latest.tgz gs://grayst0-deploy/latest.tgz
        gsutil cp /workspace/VERSION    gs://grayst0-deploy/VERSION

timeout: "1200s"
options:
  logging: CLOUD_LOGGING_ONLY
