# ─────────────────────────────── Cloud Build ────────────────────────────────
# Writes all logs to a dedicated bucket and keeps Cloud Logging clean.
logsBucket: gs://grayst0-build-logs-1746335095

options:
  logging: GCS_ONLY          # don’t duplicate logs in Cloud Logging

# ────────────────────────────────── Steps ────────────────────────────────────
steps:

# 1. Build & run unit / smoke tests inside a slim Python image
- name: python:3.11-slim
  id: build-and-test
  entrypoint: bash
  args:
    - -c
    - |
      echo "📦 installing deps …"
      pip install -q -r requirements.txt
      echo "🧪 running smoke tests …"
      pytest -q tests/smoke

# 2. Package workspace into a tarball & push to the artefact bucket
- name: gcr.io/cloud-builders/gsutil
  id: pack-and-upload
  entrypoint: bash
  args:
    - -c
    - |
      echo "📦  archiving workspace …"
      tar czf /tmp/latest.tgz .
      echo "${COMMIT_SHA:0:8}" > /tmp/VERSION
      gsutil cp /tmp/latest.tgz gs://grayst0-deploy/latest.tgz
      gsutil cp /tmp/VERSION     gs://grayst0-deploy/VERSION

# 3. Wait until the sandbox VM writes SMOKE_PASS, then promote artefact
- name: gcr.io/cloud-builders/gsutil
  id: promote-if-pass
  entrypoint: bash
  args:
    - -c
    - |
      echo "🚦 waiting for sandbox SMOKE_PASS …"
      until gsutil ls gs://grayst0-deploy/SMOKE_PASS 1>/dev/null 2>&1; do
        sleep 5
      done
      echo "✅ sandbox passed – promoting"
      gsutil cp gs://grayst0-deploy/latest.tgz gs://grayst0-prod/latest.tgz
      printf 'promoted %s\n' "${COMMIT_SHA:0:8}" | \
        gsutil cp - gs://grayst0-deploy/PROMOTIONS

# 4. Auto-maintain: create PRs / tag releases etc.
- name: python:3.11-slim          # ← use python image so `python` is present
  id: auto-maintain
  entrypoint: bash
  args:
    - -c
    - |
      pip install -q -r scripts/maintain/requirements.txt
      echo "🤖 running auto-maintain …"
      python scripts/auto-maintain.py

# ───────────────────────────────── Artifacts ────────────────────────────────
artifacts:
  objects:
    location: gs://grayst0-deploy
    paths: [ /tmp/latest.tgz, /tmp/VERSION ]

timeout: 900s   # 15 minutes – adjust if your build occasionally runs longer
