# ───────────────────────────── cloudbuild.yaml ──────────────────────────────
substitutions:
  _DEPLOY_BUCKET: gs://grayst0-deploy

steps:
  # 1. Build + run unit-/smoke-tests
  - id: build-and-test
    name: python:3.11-slim
    entrypoint: bash
    args:
      - -c
      - |
        echo "📦 installing deps …"
        pip install -q -r requirements.txt
        echo "🧪 running smoke tests …"
        pytest -q tests/smoke

  # 2. Tar up the workspace and push artefact + VERSION
  - id: pack-and-upload
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - -c
      - |
        echo "📦  archiving workspace …"
        TAR=/tmp/latest.tgz
        git rev-parse --short HEAD > /tmp/VERSION
        tar czf "$TAR" .
        gsutil cp "$TAR"       ${_DEPLOY_BUCKET}/latest.tgz
        gsutil cp /tmp/VERSION ${_DEPLOY_BUCKET}/VERSION

  # 3. Wait for sandbox to report smoke-OK, then promote
  - id: promote-if-pass
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - -c
      - |
        echo "🚦 waiting for sandbox SMOKE_PASS …"
        VERSION="$(cat /tmp/VERSION)"
        until gsutil cat ${_DEPLOY_BUCKET}/SMOKE_PASS 2>/dev/null | grep -q "$VERSION"; do
          sleep 5
        done
        echo "✅ sandbox passed – promoting"
        gsutil cp ${_DEPLOY_BUCKET}/latest.tgz  ${_DEPLOY_BUCKET}/prod.tgz
        printf '%s\n' "$VERSION" | gsutil cp - ${_DEPLOY_BUCKET}/PROD_VERSION

  # 4. Auto-maintain: bump README badges, tag release, etc.
  - id: make-and-commit-changes
    name: python:3.11-slim          # <-- the fix: gives us python in PATH
    entrypoint: bash
    args:
      - scripts/auto-maintain.sh

timeout: 900s
# ────────────────────────────────────────────────────────────────────────────
