# cloudbuild.yaml  — baseline, always green
logsBucket: gs://grayst0-build-logs-1746335095

steps:
############################################################################
# 0) tests
############################################################################
- id: build-and-test
  name: python:3.11-slim
  entrypoint: bash
  args:
    - -euoc
    - |
      echo "📦 installing deps …"
      pip install --quiet pytest requests pyyaml -r requirements.txt
      echo "🧪 running smoke tests …"
      pytest -q tests/smoke

############################################################################
# 1) pack → sandbox bucket
############################################################################
- id: pack-and-upload
  name: gcr.io/cloud-builders/gsutil
  waitFor: [build-and-test]
  entrypoint: bash
  args:
    - -euoc
    - |
      echo "📦  archiving workspace …"
      tar -czf /tmp/latest.tgz --exclude=.git .
      echo "$SHORT_SHA" > /tmp/VERSION
      gsutil cp /tmp/latest.tgz gs://grayst0-deploy/latest.tgz
      gsutil cp /tmp/VERSION    gs://grayst0-deploy/VERSION
