# ---------------------------------------------------------------------------
# Cloud Build pipeline for grayst0-live-trader
# ---------------------------------------------------------------------------

# Send build logs to the dedicated bucket
logsBucket: gs://grayst0-build-logs-1746335095

options:
  substitutionOption: ALLOW_LOOSE   # unknown _VARS won’t break the build

# ---------------------------------------------------------------------------
# Secrets
# ---------------------------------------------------------------------------
availableSecrets:
  secretManager:
    # Inject   GITHUB_PAT   → available in the steps as $GITHUB_PAT
    - versionName: projects/$(PROJECT_ID)/secrets/GITHUB_PAT/versions/latest
      env: GITHUB_PAT

# ---------------------------------------------------------------------------
# Build steps
# ---------------------------------------------------------------------------
steps:

# 0️⃣  Run smoke tests in a clean Python 3.11 image
- id: build-and-test
  name: python:3.11-slim
  entrypoint: bash
  args:
    - -ceu
    - |
      echo "📦 installing deps …"
      pip install --quiet --no-cache-dir pytest requests pyyaml -r requirements.txt
      echo "🧪 running smoke tests …"
      python -m pytest -q tests/smoke/

# 1️⃣  Archive workspace → gs://grayst0-deploy/latest.tgz  +  VERSION file
- id: pack-and-upload
  name: gcr.io/cloud-builders/gsutil
  entrypoint: bash
  args:
    - -ceu
    - |
      echo "📦  archiving workspace …"
      tar -czf /tmp/latest.tgz --exclude=.git .
      echo "$COMMIT_SHA" > /tmp/VERSION
      gsutil cp /tmp/latest.tgz gs://grayst0-deploy/latest.tgz
      gsutil cp /tmp/VERSION    gs://grayst0-deploy/VERSION

# 2️⃣  Wait for sandbox VM to post SMOKE_PASS → promote to “prod”
- id: promote-if-pass
  name: gcr.io/cloud-builders/gsutil
  waitFor: ['pack-and-upload']
  entrypoint: bash
  args:
    - -ceu
    - |
      echo "🚦 waiting for sandbox SMOKE_PASS …"
      for i in {1..30}; do        # 5 min max (30×10 s)
        if gsutil cat gs://grayst0-deploy/SMOKE_PASS 2>/dev/null \
             | grep -q "$SHORT_SHA"; then
          echo "✅ sandbox passed – promoting"
          gsutil cp gs://grayst0-deploy/latest.tgz gs://grayst0-prod/latest.tgz
          echo "$SHORT_SHA" | gsutil cp - gs://grayst0-deploy/PROD_PASS
          exit 0
        fi
        sleep 10
      done
      echo "🛑 sandbox did not approve within 5 min"
      exit 1

# 3️⃣  Run the repo’s auto-maintenance script and push changes
- id: auto-maintain
  name: python:3.11-slim
  waitFor: ['promote-if-pass']
  entrypoint: bash
  env:
    - GITHUB_PAT=$$GITHUB_PAT        # KEY=VALUE form required
    - GIT_AUTHOR_NAME=cloudbuild
    - GIT_AUTHOR_EMAIL=ci@grayst0
    - GIT_COMMITTER_NAME=cloudbuild
    - GIT_COMMITTER_EMAIL=ci@grayst0
  args:
    - -ceu
    - |
      echo "🛠️  running auto-maintenance …"
      export GITHUB_TOKEN="$$GITHUB_PAT"
      pip install --quiet -r scripts/requirements-auto.txt
      ./scripts/auto-maintain.sh
      echo "🚀 auto-maintenance finished"

# ---------------------------------------------------------------------------
# No container images are pushed by this build
# ---------------------------------------------------------------------------
images: []

# Handy custom substitutions (optional)
substitutions:
  _DEPLOY_BUCKET: gs://grayst0-deploy
