steps:
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: /bin/bash
    args:
      - -eu
      - -c
      - |
        TAR="deploy-\$COMMIT_SHA.tgz"
        git archive --format=tar.gz -o "\$TAR" --prefix=app/ \$COMMIT_SHA
        gsutil cp "\$TAR" gs://grayst0-deploy/
substitutions:
  _COMMIT_SHA: ${REVISION_ID}
timeout: 300s
options: {logging: CLOUD_LOGGING_ONLY}
