# ---------------------------------------------------------------------------
# Cloud Build pipeline for grayst0-live-trader
# ---------------------------------------------------------------------------

# (1) Send all build logs to the dedicated bucket we just created.
logsBucket: gs://grayst0-build-logs-1746335095        # ← new

# (2) Allow loose substitutions so unknown _VARS don’t break the build.
options:
  substitutionOption: ALLOW_LOOSE

# ---------------------------------------------------------------------------
# Build steps
# ---------------------------------------------------------------------------
steps:

##############################################################################
# 0. Run unit / smoke tests in a clean 3.11 environment
##############################################################################
- id: build-and-test
  name: python:3.11-slim
  entrypoint: bash
  args:
    - -euoc
    - |
      echo "📦 installing deps …"
      pip install -r requirements.txt
      echo "🧪 running smoke tests …"
      pytest tests/smoke

##############################################################################
# 1. Archive the workspace → gs://grayst0-deploy/latest.tgz  +  VERSION file
##############################################################################
- id: pack-and-upload
  name: gcr.io/cloud-builders/gsutil
  entrypoint: bash
  args:
    - -euoc
    - |
      TMP=/tmp/latest.tgz
      echo "📦  archiving workspace …"
      tar -czf "$TMP" .
      gsutil cp "$TMP" gs://grayst0-deploy/latest.tgz
      echo "$COMMIT_SHA" > /tmp/VERSION
      gsutil cp /tmp/VERSION gs://grayst0-deploy/VERSION

##############################################################################
# 2. Wait for the sandbox VM to post SMOKE_PASS → promote artefact to “prod”
##############################################################################
- id: promote-if-pass
  name: gcr.io/cloud-builders/gsutil
  waitFor: ['pack-and-upload']
  entrypoint: bash
  args:
    - -euoc
    - |
      echo "🚦 waiting for sandbox SMOKE_PASS …"
      until gsutil -q stat gs://grayst0-deploy/SMOKE_PASS ; do
        sleep 5
      done
      echo "✅ sandbox passed – promoting"
      gsutil cp gs://grayst0-deploy/latest.tgz gs://grayst0-prod/latest.tgz
      printf 'prod-OK %s\n' "$COMMIT_SHA" | gsutil cp - gs://grayst0-deploy/PROD_PASS

##############################################################################
# 3. Run the repo’s auto-maintenance script (now in a proper python image)
##############################################################################
- id: make-and-commit-changes
  name: python:3.11-slim                # ← switched from git → python image
  waitFor: ['promote-if-pass']
  entrypoint: bash
  env:
    # git will use these when auto-committing generated files
    - GIT_AUTHOR_NAME=cloudbuild
    - GIT_AUTHOR_EMAIL=ci@grayst0
    - GIT_COMMITTER_NAME=cloudbuild
    - GIT_COMMITTER_EMAIL=ci@grayst0
  args:
    - -euoc
    - |
      pip install -r scripts/requirements-auto.txt   # deps for auto-maintain
      ./scripts/auto-maintain.sh

# ---------------------------------------------------------------------------
# No images are pushed by this build
# ---------------------------------------------------------------------------
images: []

# ---------------------------------------------------------------------------
# Handy custom substitutions (none are strictly required)
# ---------------------------------------------------------------------------
substitutions:
  _PY_VERSION: "3.11"
